In [7]:
#Create Arrays
import numpy as np

a = np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [3]:
b = np.arange(1,11)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
c = np.linspace(0,1,5)
print(c)

[0.   0.25 0.5  0.75 1.  ]


In [9]:
#Matrix operation
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A+B)
print(A-B)
print(A*B)
print(A@B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [12]:
#Statistics
marks = np.array([70,65,80,90,88])

print(np.mean(marks))
print(np.min(marks))
print(np.max(marks))
print(np.std(marks))

78.6
65
90
9.789790600416334


In [18]:
#Temperature
temp = np.array([29, 29, 29, 26, 27, 28, 29, 30, 32, 32, 32, 33, 33, 34, 33, 32, 31, 30, 31, 28, 31, 29, 26, 30, 29, 31, 30, 29, 28, 28, 29])
max_temp = np.max(temp)
min_temp = np.min(temp)
avg_temp = np.mean(temp)


In [16]:
hottest_day = np.argmax(temp) + 1
coldest_day = np.argmin(temp) + 1

In [19]:
print(f"Hottest Temperature : {max_temp}°C on July {hottest_day}, 2026")
print(f"Coldest Temperature : {min_temp}°C on July {coldest_day}, 2026")
print(f"Average Temperature : {avg_temp:.2f}°C")

Hottest Temperature : 34°C on July 14, 2026
Coldest Temperature : 26°C on July 4, 2026
Average Temperature : 29.94°C
